FROM maven:3.9-eclipse-temurin-17 AS build
WORKDIR /build
COPY pom.xml .
RUN mvn -q -B dependency:go-offline
COPY src ./src
RUN mvn -q -B -DskipTests package
FROM eclipse-temurin:17-jre
WORKDIR /app
COPY --from=build /build/target/gateway-*.jar app.jar
ENV TZ=Asia/Shanghai
EXPOSE 8000
ENTRYPOINT ["java","-jar","/app/app.jar"]
